### ISSUE TITLE
objects/Status: regexp doesn't match to MPD specification

### ISSUE THREAD

**Issue by ribizli** [hbenl/mpc-js-core#1]
From the MPD specification:
> Always open the audio output with the specified audio format (samplerate:bits:channels), regardless of the format of the input file. This is optional for most plugins.

>Any of the three attributes may be an asterisk to specify that this attribute should not be enforced, example: 48000:16:*. *:*:* is equal to not having a format specification.

>The following values are valid for bits: 8 (signed 8 bit integer samples), 16, 24 (signed 24 bit integer samples padded to 32 bit), 32 (signed 32 bit integer samples), f (32 bit floating point, -1.0 to 1.0), "dsd" means DSD (Direct Stream Digital). For DSD, there are special cases such as "dsd64", which allows you to omit the sample rate (e.g. dsd512:2 for stereo DSD512, i.e. 22.5792 MHz).

The `audioRegEx = /([0-9]+):([0-9]+):([0-9]+)/;` accepts only digits.
However `*`, `f`, `dsd`, etc are also valid values for `bits`.

I get the following exception, since the regexp doesn't match:

```
TypeError: Cannot read property '1' of null
    at new Status (...\node_modules\mpc-js-core\lib\objects\status.js:19:43)
```
Anyway it would be a good idea, to check for match before accessing the groups.

**Comment by hbenl** [comment]
I was not aware of this, thanks for pointing it out!
I have taken a slightly different approach than in your patch - `audio` is now split by `:` and each of `samplerate`, `bitDepth` and `channels` is filled individually if it can be parsed as a number (so if one of them is a number and the others aren't, it will still be parsed) and `Status` now also has a property `audio` containing the unparsed `audio` field from MPD's status message.

**Comment by ribizli** [comment]
During my build I got difficulties with the latest TypeScript (`2.4.2`) to compile. Check my fork's commit what I needed to change to work.
I also needed to remove (temporarily) the typedoc package, it caused some typing errors as well (`@types/highlight.js`; missing `dom` lib from tsconfig?).

**Comment by hbenl** [comment]
Yes, I saw that, but I had already created a similar fix for these issues yesterday, I just hadn't published it yet, but they are in the latest version now.
Thinking about it now made me realise that one should always set the typescript dependency to `~x.y.z` instead of `^x.y.z` because typescript often introduces breaking changes in their minor releases (unlike [what semantic versioning demands](https://docs.npmjs.com/getting-started/semantic-versioning))

**Comment by ribizli** [comment]
I've just realized that the `Song` as return type among the database commands is correct, since only songs can be returned. So my fix is wrong in that case. Maybe a casting can do it.
It wasn't necessarily a breaking change, just TypeScript does type checking even better. In that case it has right, `Song` is more specific as `DirectoryEntry`.

Anyway, thanks for the quick solution, I can now remove my quickfix from our nexus and use again your public version. (BTW in the next weeks we will use your library heavily for a project, expect some more feedback from me).
