### ISSUE TITLE
`ID not found for PlaylistItem object` when listing stored playlists

### ISSUE THREAD

**Issue by anddon** [hbenl/mpc-js-core#10]
The `listPlaylistInfo` seems to be broken, as the song entries that the server sends lack the `id` property.
I think that `id` and `pos` are only suppose to be present in the current playlist payloads, not the stored playlists.

From what I see the cause for this is `if (!valueMap.has('Id')) throw new Error('ID not found for PlaylistItem object');` in commit https://github.com/hbenl/mpc-js-core/commit/4edbf89c328ad3cb8d6320d76138eff64c001c40

Maybe we can relax the type for `PlaylistItem` to have `id` and `pos` `number | undefined`

I'm using `MPD 0.21.11`

**Comment by hbenl** [comment]
> I think that id and pos are only suppose to be present in the current playlist payloads, not the stored playlists.

Yes, apparently they are.
Thanks for the bug report and the fix!
