### ISSUE TITLE
Grouping does not work properly for list command

### ISSUE THREAD

**Issue by JakeStanger** [hbenl/mpc-js-core#13]
I suspect this is an issue if grouping exists elsewhere, but for the `list` command the returned map is a jumble of incorrect keys and values.

The following code:
```ts
client.database.list('Album', [], ['Artist']).then(console.log);
```
Produces a map where the first key is the first album name, then the second key is an empty string `''` and the value is almost every album. 
![image](https://user-images.githubusercontent.com/5057870/94351093-133a4600-004d-11eb-9d3b-243bf57feab2.png)

Every other entry has an artist name key and a single album value, but these are all shifted by one (each album is paired with the previous artist).
![image](https://user-images.githubusercontent.com/5057870/94351098-23eabc00-004d-11eb-9f2e-22457c3b3477.png)
> In the above example, Brand X wrote *Xcommunication*, Eno wrote *The Ship*, Eno & Bryne wrote *My Life...*, etc...

**Comment by hbenl** [comment]
Fixed in version 1.3.2
