### ISSUE TITLE
database.list() marker: lowercase not supported

### ISSUE THREAD

**Issue by ribizli** [hbenl/mpc-js-core#2]
Regarding MPD [docs](https://www.musicpd.org/doc/protocol/tags.html) the tags to use for database command `list {type}` is lowercase. MPD however returns results with capital letter (e.g. Album, Artist).

It is not possible to query like this: `mpc.database.list('album')`.

It returns: `Map {[] => [undefined]}`

**Comment by hbenl** [comment]
Yes, the MPD documentation is incorrect in this regard - I've added some documentation regarding this, telling users to use `mpc.reflection.tagTypes()` to get the correct list of supported tags.
