### ISSUE TITLE
Add support for multiple genre tags

### ISSUE THREAD

**Issue by anddon** [hbenl/mpc-js-core#7]
Is there any chance we can add support for multiple genre tags?
MPD handles this by sending the `Genre:` key multiple times, so it should be parsed in an array.
I could help with the PR, but I'm not very versed in Typescript, so I could use a bit of guidance.
Thanks.

**Comment by hbenl** [comment]
I did some research and it seems that there is no consensus about how to handle multiple genres (and many mp3 clients don't support that at all): some people use multiple `Genre` tags, others put the genres into one `Genre` tag (and there's no consensus on what separator character to use, but `;` seems to be the most common).
So I thought I'd keep the existing `genre: string` property and put multiple genres in there, separated by `;`. That would ensure compatibility with existing consumers of this library and you could then get the full list of genres like this: `song.genre.split(";")`.
Would that work for you?

**Comment by anddon** [comment]
I think that would be a good compromise and, like you said, similar to how most players and tag editors with support for multiple identical tags handle it.
I'll take a stab at a PR for this.

**Comment by hbenl** [comment]
LGTM
